setwd("d:/R_files/CoURSERA")
data_household<-read.csv('household_power_consumption.txt',header=T, sep=";", dec=".", na.strings=c("?"))
data_household2<-data_household[66637:69517,]
datetime<-as.POSIXct(paste(data_household2$Date,data_household2$Time), format="%d/%m/%Y %H:%M:%S")
data_household3<-cbind(data_household2,datetime)
remove(datetime)
png(filename = "plot3.png", width = 480, height = 480)
with(data_household3,plot(datetime,Sub_metering_1,ylab="Energy sub metering", type="n",xlab=""),ylim=c(0,40))
with(data_household3,lines(datetime,Sub_metering_1,col="black"))
with(data_household3,lines(datetime,Sub_metering_2,col="red"))
with(data_household3,lines(datetime,Sub_metering_3,col="blue"))
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.off()